### ISSUE TITLE
Handheld shortwave bug

### ISSUE THREAD

**Issue by LettereUniche** [Fuar11/ImprovedSignalVoid#1]
Hello,

After equipping the handheld shortwave during an aurora/glimmer fog, both the small light on the side and the dial of the radio isn't working as intended.

Basically once equipped, the dial won't move and the light won't blink even if im getting closer to the signal. However by unequpping and then equipping it or by doing anything that would take of the radio from your screen (e.g opening inventory), the radio emits a noise, the dial may move and the light may start blinking depending on how close you are to the signal, but after that it won't change.

You can still uncover supply caches and bunkers, but it is slightly hard to find them like this.

I did test it without any other mods (expect the ones required to run this one) and got the same result.

**Comment by Fuar11** [comment]
Fixed in latest release
